name: LeveledMobs
main: org.shatteredrealms.leveledmobs.LeveledMobs
version: 19.0

commands:
   lm:
      description: Main LeveledMobs command

softdepend: [WorldEdit, WorldGuard, ControllableMobsAPI]